export const companies = [
    { name: "Booking Holdings Inc.", symbol: "BKNG" },
    { name: "First Citizens BancShares, Inc.", symbol: "FCNCA" },
    { name: "MercadoLibre, Inc.", symbol: "MELI" },
    { name: "Broadcom Inc.", symbol: "AVGOP" },
    { name: "MicroStrategy Incorporated", symbol: "MSTR" },
    { name: "Coca-Cola Consolidated, Inc.", symbol: "COKE" },
    { name: "O'Reilly Automotive, Inc.", symbol: "ORLY" },
    { name: "Regeneron Pharmaceuticals, Inc.", symbol: "REGN" },
    { name: "ASML Holding N.V.", symbol: "ASML" },
    { name: "Costco Wholesale Corporation", symbol: "COST" },
    { name: "Monolithic Power Systems, Inc.", symbol: "MPWR" },
    { name: "Equinix, Inc.", symbol: "EQIX" },
    { name: "Lam Research Corporation", symbol: "LRCX" },
    { name: "Cintas Corporation", symbol: "CTAS" },
    { name: "KLA Corporation", symbol: "KLAC" },
    { name: "Super Micro Computer, Inc.", symbol: "SMCI" },
    { name: "Intuit Inc.", symbol: "INTU" },
    { name: "Netflix, Inc.", symbol: "NFLX" },
    { name: "Roper Technologies, Inc.", symbol: "ROP" },
    { name: "Adobe Inc.", symbol: "ADBE" },
    { name: "National Western Life Group, Inc.", symbol: "NWLI" },
    { name: "Synopsys, Inc.", symbol: "SNPS" },
    { name: "Meta Platforms, Inc.", symbol: "META" },
    { name: "argenx SE", symbol: "ARGX" },
    { name: "Vertex Pharmaceuticals Incorporated", symbol: "VRTX" },
    { name: "Credit Acceptance Corporation", symbol: "CACC" },
    { name: "IDEXX Laboratories, Inc.", symbol: "IDXX" },
    { name: "Atrion Corporation", symbol: "ATRI" },
    { name: "Intuitive Surgical, Inc.", symbol: "ISRG" },
    { name: "Linde plc", symbol: "LIN" },
    { name: "Erie Indemnity Company", symbol: "ERIE" },
    { name: "Daily Journal Corporation", symbol: "DJCO" },
    { name: "Microsoft Corporation", symbol: "MSFT" },
    { name: "Saia, Inc.", symbol: "SAIA" },
    { name: "Abiomed, Inc.", symbol: "ABMD" },
    { name: "Medpace Holdings, Inc.", symbol: "MEDP" },
    { name: "Casey's General Stores, Inc.", symbol: "CASY" },
    { name: "Wingstop Inc.", symbol: "WING" },
    { name: "Cavco Industries, Inc.", symbol: "CVCO" },
    { name: "Charter Communications, Inc.", symbol: "CHTR" },
    { name: "Pool Corporation", symbol: "POOL" },
    { name: "Winmark Corporation", symbol: "WINA" },
    { name: "ShockWave Medical, Inc.", symbol: "SWAV" },
    { name: "Karuna Therapeutics, Inc.", symbol: "KRTX" },
    { name: "Amgen Inc.", symbol: "AMGN" },
    { name: "Ulta Beauty, Inc.", symbol: "ULTA" },
    { name: "Enstar Group Limited", symbol: "ESGR" },
    { name: "United Therapeutics Corporation", symbol: "UTHR" },
    { name: "Zebra Technologies Corporation", symbol: "ZBRA" },
    { name: "ICON Public Limited Company", symbol: "ICLR" },
    { name: "UFP Technologies, Inc.", symbol: "UFPT" },
    { name: "CSW Industrials, Inc.", symbol: "CSWI" },
    { name: "ANSYS, Inc.", symbol: "ANSS" },
    { name: "Morningstar, Inc.", symbol: "MORN" },
    { name: "Palo Alto Networks, Inc.", symbol: "PANW" },
    { name: "CorVel Corporation", symbol: "CRVL" },
    { name: "Axon Enterprise, Inc.", symbol: "AXON" },
    { name: "Encore Wire Corporation", symbol: "WIRE" },
    { name: "Willis Towers Watson Public Limited Company", symbol: "WLTW" },
    { name: "Madrigal Pharmaceuticals, Inc.", symbol: "MDGL" },
    { name: "Alnylam Pharmaceuticals, Inc.", symbol: "ALNY" },
    { name: "Verisk Analytics, Inc.", symbol: "VRSK" },
    { name: "Tractor Supply Company", symbol: "TSCO" },
    { name: "Cadence Design Systems, Inc.", symbol: "CDNS" },
    { name: "Automatic Data Processing, Inc.", symbol: "ADP" },
    { name: "WD-40 Company", symbol: "WDFC" },
    { name: "CyberArk Software Ltd.", symbol: "CYBR" },
    { name: "Manhattan Associates, Inc.", symbol: "MANH" },
    { name: "Lululemon Athletica Inc.", symbol: "LULU" },
    { name: "NXP Semiconductors N.V.", symbol: "NXPI" },
    { name: "Littelfuse, Inc.", symbol: "LFUS" },
    { name: "Nordson Corporation", symbol: "NDSN" },
    { name: "MarketAxess Holdings Inc.", symbol: "MKTX" },
    { name: "Autodesk, Inc.", symbol: "ADSK" },
    { name: "CrowdStrike Holdings, Inc.", symbol: "CRWD" },
    { name: "Seagen Inc.", symbol: "SGEN" },
    { name: "Hingham Institution for Savings", symbol: "HIFS" },
    { name: "Tetra Tech, Inc.", symbol: "TTEK" },
    { name: "II-VI Incorporated", symbol: "IIVI" },
    { name: "MongoDB, Inc.", symbol: "MDB" },
    { name: "SBA Communications Corporation", symbol: "SBAC" },
    { name: "Marriott International, Inc.", symbol: "MAR" },
    { name: "RBC Bearings Incorporated", symbol: "ROLL" },
    { name: "Workday, Inc.", symbol: "WDAY" },
    { name: "First Solar, Inc.", symbol: "FSLR" },
    { name: "monday.com Ltd.", symbol: "MNDY" },
    { name: "CDW Corporation", symbol: "CDW" },
    { name: "AppFolio, Inc.", symbol: "APPF" },
    { name: "Apple Inc.", symbol: "AAPL" },
    { name: "Align Technology, Inc.", symbol: "ALGN" },
    { name: "Analog Devices, Inc.", symbol: "ADI" },
    { name: "Sanderson Farms, Inc.", symbol: "SAFM" },
    { name: "Investors Title Company", symbol: "ITIC" },
    { name: "CME Group Inc.", symbol: "CME" },
    { name: "Tesla, Inc.", symbol: "TSLA" },
    { name: "Biogen Inc.", symbol: "BIIB" },
    { name: "Prometheus Biosciences, Inc.", symbol: "RXDX" },
    { name: "Honeywell International Inc.", symbol: "HON" },
    { name: "Old Dominion Freight Line, Inc.", symbol: "ODFL" },
];
